- name: Install Azure DevOps Self-Hosted Agent
  hosts: agents
  become: true

  vars:
    agent_user: "azureuser"
    agent_dir: "/home/aristotle/adoagent"
    azure_devops_org: "101516795-Savvy"
    azure_devops_pat: "EeCsFmhftfcZMZE1p2vVasKdLfz0XmZF8wubmAfQN4IEgPOJhTeOJQQJ99BFACAAAAAbsQ3UAAASAZDObHmR"
    azure_devops_pool: "Default"
    azure_devops_url: "https://dev.azure.com/101516795-Savvy"

  tasks:
    - name: Install basic dependencies
      apt:
        name:
          - curl
          - libcurl4
          - libssl-dev
          - jq
        state: present
        update_cache: yes
    
    - name: Download Azure DevOps agent
      become_user: "{{ agent_user }}"
      shell: |
        cd {{ agent_dir }}
        curl -O --insecure https://vstsagentpackage.azureedge.net/agent/3.236.0/vsts-agent-linux-x64-3.236.0.tar.gz
        tar zxvf vsts-agent-linux-x64-3.236.0.tar.gz
      args:
        creates: "{{ agent_dir }}/config.sh"


    - name: Configure the agent
      become_user: "{{ agent_user }}"
      shell: |
        ./config.sh --unattended \
        --url {{ azure_devops_url }} \
        --auth pat \
        --token {{ azure_devops_pat }} \
        --pool {{ azure_devops_pool }} \
        --agent ansible-host \
        --acceptTeeEula
      args:
        chdir: "{{ agent_dir }}"

    - name: Install agent as service
      become_user: "{{ agent_user }}"
      shell: |
        sudo ./svc.sh install
        sudo ./svc.sh start
      args:
        chdir: "{{ agent_dir }}"
